import React, {useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {samples,emotions,contexts} from './data';
import './style.css';

const fresh=()=>({emotion:'',valence:0,arousal:0.5,confidence:3,evidence:[],notes:'',start:0,end:0});
const time=n=>`${Number(n||0).toFixed(2)} s`;
const palette={Anger:'#fd9a7d',Happiness:'#b4ef77',Neutral:'#a8bbc7',Sadness:'#94b6ff'};
function readSaved(){try{return JSON.parse(localStorage.getItem('edl-annotations-v1')||'[]')}catch{return []}}
function downloadJSON(data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='emotion-dynamics-annotations.json';a.click();URL.revokeObjectURL(url)}

function Signal({url,audioRef,position,onSeek,onDuration,onError}){
  const wave=useRef(),spectrum=useRef(),[buffer,setBuffer]=useState(null),[zoom,setZoom]=useState(1),[offset,setOffset]=useState(0);
  useEffect(()=>{let alive=true;let ac;setBuffer(null);setZoom(1);setOffset(0);
    (async()=>{try{const response=await fetch(url);if(!response.ok)throw Error('Audio file unavailable');ac=new AudioContext();const decoded=await ac.decodeAudioData(await response.arrayBuffer());if(alive){setBuffer(decoded);onDuration(decoded.duration);onError('')}}catch(e){if(alive)onError('Could not decode this audio. Try a WAV or MP3 file.')}finally{if(ac)ac.close()}})();return()=>{alive=false};
  },[url]);
  useEffect(()=>{if(!buffer)return;const canvas=wave.current,ctx=canvas.getContext('2d'),w=1000,h=190;canvas.width=w;canvas.height=h;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#304047';ctx.lineWidth=1;for(let y=25;y<h;y+=35){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}
    const data=buffer.getChannelData(0),length=buffer.duration/zoom,start=offset*buffer.sampleRate;ctx.strokeStyle='#b4ef77';ctx.lineWidth=1.5;ctx.beginPath();for(let x=0;x<w;x++){const a=Math.floor(start+x*length*buffer.sampleRate/w),b=Math.min(data.length,Math.ceil(start+(x+1)*length*buffer.sampleRate/w));let lo=0,hi=0;for(let i=a;i<b;i++){lo=Math.min(lo,data[i]);hi=Math.max(hi,data[i])}ctx.moveTo(x,h/2+lo*(h/2-10));ctx.lineTo(x,h/2+hi*(h/2-10))}ctx.stroke();
    const px=(position-offset)/length*w;if(px>=0&&px<=w){ctx.strokeStyle='#ffffff';ctx.beginPath();ctx.moveTo(px,0);ctx.lineTo(px,h);ctx.stroke()}
  },[buffer,position,zoom,offset]);
  useEffect(()=>{if(!buffer)return;const c=spectrum.current,g=c.getContext('2d');c.width=1000;c.height=120;g.clearRect(0,0,1000,120);
    const n=512,data=buffer.getChannelData(0),base=Math.max(0,Math.min(data.length-n,Math.floor(position*buffer.sampleRate))),bins=128;
    for(let k=1;k<=bins;k++){let re=0,im=0;for(let j=0;j<n;j++){const v=(data[base+j]||0)*(0.5-0.5*Math.cos(2*Math.PI*j/(n-1)));re+=v*Math.cos(2*Math.PI*k*j/n);im-=v*Math.sin(2*Math.PI*k*j/n)}const db=20*Math.log10(Math.max(1e-6,Math.hypot(re,im)/n));const height=Math.max(0,Math.min(110,(db+90)/90*110));g.fillStyle=`hsl(${180+k/3} 45% ${35+k/6}%)`;g.fillRect((k-1)*1000/bins,120-height,1000/bins-2,height)}
  },[buffer,position]);
  return <div className="signal"><div className="signal-heading"><span>WAVEFORM <small>Amplitude · mono channel</small></span><label>Zoom <select value={zoom} onChange={e=>{setZoom(+e.target.value);setOffset(0)}}><option value="1">1×</option><option value="2">2×</option><option value="4">4×</option></select></label></div><canvas aria-label="Waveform; click to seek" ref={wave} onClick={e=>{if(buffer){const r=e.currentTarget.getBoundingClientRect();onSeek(offset+(e.clientX-r.left)/r.width*buffer.duration/zoom)}}}/><div className="axis"><span>{time(offset)}</span><span>{buffer?`${(buffer.sampleRate/1000).toFixed(1)} kHz · ${buffer.numberOfChannels} ch`:'Loading audio…'}</span><span>{time(offset+(buffer?.duration||0)/zoom)}</span></div>{zoom>1&&<label className="pan">Pan <input type="range" min="0" max={(buffer?.duration||0)*(1-1/zoom)} step="0.01" value={offset} onChange={e=>setOffset(+e.target.value)}/></label>}<div className="spectrum-head">FREQUENCY SPECTRUM <small>At playhead · 512-sample Hann window</small></div><canvas className="spectrum" ref={spectrum} aria-label="Frequency spectrum at current playhead"/><div className="axis"><span>0 Hz</span><span>Magnitude (−90 to 0 dBFS, display scale)</span><span>{buffer?`${(buffer.sampleRate/4000).toFixed(1)} kHz`:''}</span></div></div>
}

function App(){
 const [clips,setClips]=useState(samples),[id,setId]=useState(samples[0].id),[query,setQuery]=useState(''),[actor,setActor]=useState('all'),[context,setContext]=useState('none'),[custom,setCustom]=useState(''),[showText,setShowText]=useState(true),[reveal,setReveal]=useState(false),[position,setPosition]=useState(0),[duration,setDuration]=useState(0),[error,setError]=useState(''),[annotation,setAnnotation]=useState(fresh),[saved,setSaved]=useState(readSaved),[status,setStatus]=useState(''),[tab,setTab]=useState('explore'),[database,setDatabase]=useState(false),[saving,setSaving]=useState(false),[compare,setCompare]=useState(''),[loop,setLoop]=useState(false);
 const audio=useRef(),importInput=useRef(),compareAudio=useRef(),blobURLs=useRef([]);
 const clip=clips.find(c=>c.id===id)||clips[0];const peers=clips.filter(c=>c.group===clip.group&&c.text===clip.text&&c.id!==id);const comparison=peers.find(c=>c.id===compare);
 const contextText=context==='custom'?custom:contexts[context].text;
 const filtered=clips.filter(c=>(actor==='all'||c.speaker===actor)&&`${c.text} ${c.id} ${c.language}`.toLowerCase().includes(query.toLowerCase()));
 useEffect(()=>{fetch('/api/health').then(r=>r.ok?r.json():null).then(x=>setDatabase(x?.storage==='sqlite')).catch(()=>{});return()=>blobURLs.current.forEach(URL.revokeObjectURL)},[]);
 useEffect(()=>{localStorage.setItem('edl-annotations-v1',JSON.stringify(saved))},[saved]);
 function select(next){audio.current?.pause();compareAudio.current?.pause();setId(next);setPosition(0);setDuration(0);setCompare('');setAnnotation(fresh());setStatus('');setReveal(false);setError('');setLoop(false)}
 function seek(t){if(audio.current){audio.current.currentTime=Math.max(0,Math.min(duration,t));setPosition(audio.current.currentTime)}}
 function update(key,value){setAnnotation(a=>({...a,[key]:value}))}
 async function save(){if(!annotation.emotion){setStatus('Choose a perceived emotion before saving.');return}if(annotation.end>0&&annotation.end<=annotation.start){setStatus('Region end must be later than its start.');return}if(annotation.start>duration||annotation.end>duration){setStatus('Region must be within the audio duration.');return}
   setSaving(true);const row={id:crypto.randomUUID(),clipId:clip.id,transcript:clip.text,source:clip.source,language:clip.language,contextCondition:context,contextText,transcriptVisible:showText,datasetLabelRevealed:reveal,comparisonClipId:comparison?.id||null,...annotation,end:annotation.end||duration,createdAt:new Date().toISOString(),labelMeaning:'listener perception; not speaker internal ground truth'};
   setSaved(v=>[...v,row]);if(database){try{const r=await fetch('/api/annotations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(row)});if(!r.ok)throw Error();setStatus('Saved to SQLite and this browser.')}catch{setStatus('Saved in this browser; database save failed. Export a backup.')}}else setStatus('Saved in this browser. Export JSON to keep a backup.');setSaving(false)
 }
 function importFiles(e){const files=[...e.target.files];const imported=files.map((f,i)=>{const url=URL.createObjectURL(f);blobURLs.current.push(url);return{id:`local-${crypto.randomUUID()}`,text:f.name,intended:'Not provided',language:'Unspecified',speaker:'Local',group:`import-${Date.now()}`,source:'Your local file · this session only',url}});if(imported.length){setClips(v=>[...v,...imported]);select(imported[0].id);setActor('all');setQuery('')}e.target.value=''}
 function VA(){return <svg className="va" viewBox="0 0 240 180" aria-label={`Valence ${annotation.valence}, arousal ${annotation.arousal}`}><rect x="30" y="10" width="180" height="135" rx="6" fill="#17242b"/><path d="M120 10V145M30 77H210" stroke="#40525a" strokeDasharray="3 5"/><text x="120" y="23" textAnchor="middle">activated</text><text x="120" y="136" textAnchor="middle">calm</text><text x="30" y="163">unpleasant</text><text x="161" y="163">pleasant</text><circle cx={30+(annotation.valence+1)*90} cy={145-annotation.arousal*135} r="6" fill="#b4ef77"/></svg>}
 return <><header><div className="brand"><span className="logo">∿</span><div>Emotion Dynamics <strong>Lab</strong><small>AUDIO / CONTEXT / PERCEPTION</small></div></div><nav><button className={tab==='explore'?'active':''} onClick={()=>setTab('explore')}>Workspace</button><button className={tab==='saved'?'active':''} onClick={()=>setTab('saved')}>Annotations <span>{saved.length}</span></button></nav><span className="storage">{database?'SQLite connected':'Browser storage'} · no model required</span></header>
 <div className="intro"><div><span className="eyebrow">RESEARCH WORKSPACE · HW1</span><h1>One sentence. Many ways to feel.</h1><p>Listen, compare, and annotate emotion in speech.</p></div><div className="intro-actions"><button onClick={()=>importInput.current.click()}>＋ Import audio</button><button onClick={()=>downloadJSON(saved)}>↓ Export annotations</button><input hidden multiple ref={importInput} type="file" accept="audio/*" onChange={importFiles}/></div></div>
 {tab==='saved'?<main className="saved-view"><div className="panel"><h2>Your listening notes <span className="count">{saved.length}</span></h2><p>Independent ratings, not a ground-truth emotion distribution. Exports include context and whether source labels were visible.</p>{saved.length===0?<div className="empty">Listen to a clip and save your first annotation.</div>:<div className="table-scroll"><table><thead><tr><th>Clip / time</th><th>Context</th><th>Emotion</th><th>VA</th><th>Confidence</th><th>Notes</th></tr></thead><tbody>{saved.map(r=><tr key={r.id}><td>{r.clipId}<small>{time(r.start)} – {time(r.end)}</small></td><td>{r.contextCondition}</td><td>{r.emotion}</td><td>{r.valence} / {r.arousal}</td><td>{r.confidence}/5</td><td>{r.notes||'—'}</td></tr>)}</tbody></table></div>}</div><button onClick={()=>setTab('explore')}>← Back to listening</button></main>:<main className="workspace"><aside className="library panel"><div className="section-label">01 / LIBRARY <span>{filtered.length} clips</span></div><input aria-label="Search clips" placeholder="Search transcript or clip ID…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter speaker" value={actor} onChange={e=>setActor(e.target.value)}><option value="all">All speakers</option>{[...new Set(clips.map(c=>c.speaker))].map(s=><option key={s}>{s}</option>)}</select><div className="clip-list">{filtered.map((c,i)=><button className={`clip ${c.id===id?'selected':''}`} key={c.id} onClick={()=>select(c.id)}><span className="clip-number">{String(i+1).padStart(2,'0')}</span><span><strong>{c.text}</strong><small>Speaker {c.speaker} · {c.language}</small><small className="mono">{c.id}</small></span><span className="clip-icon">▷</span></button>)}{!filtered.length&&<p>No clips match your search.</p>}</div><div className="library-note"><strong>CREMA-D sample collection</strong><p>15 acted recordings · 2 speakers · 2 sentences. Filename labels describe intended performances, not measured inner feelings.</p><a href="https://github.com/CheyneyComputerScience/CREMA-D" target="_blank" rel="noreferrer">Dataset & attribution ↗</a></div></aside>
 <section className="listening"><article className="panel"><div className="section-label">02 / LISTEN <span>{clip.language} · Speaker {clip.speaker}</span></div><div className="clip-title"><h2>{clip.source==='CREMA-D'?'Listen to the expression':clip.text}</h2><label className="toggle"><input type="checkbox" checked={showText} onChange={e=>setShowText(e.target.checked)}/> Transcript</label></div>{showText?<blockquote>{clip.text}</blockquote>:<blockquote className="muted">Transcript hidden for listening.</blockquote>}{clip.speaker==='Local'&&<label>Transcript <input value={clip.text} onChange={e=>setClips(v=>v.map(c=>c.id===id?{...c,text:e.target.value}:c))}/></label>}
 <audio key={clip.url} ref={audio} src={clip.url} controls preload="metadata" onPlay={()=>compareAudio.current?.pause()} onTimeUpdate={e=>{const p=e.currentTarget.currentTime;setPosition(p);if(loop&&annotation.end>annotation.start&&p>=annotation.end)e.currentTarget.currentTime=annotation.start}} onError={()=>setError('Audio could not load. See README sample-download instructions, or import your own audio.')}/>{error&&<p role="alert" className="error">{error}</p>}<Signal url={clip.url} audioRef={audio} position={position} onSeek={seek} onDuration={setDuration} onError={setError}/>
 <div className="region"><span>REGION</span><button onClick={()=>update('start',+position.toFixed(2))}>Set start {time(annotation.start)}</button><button onClick={()=>update('end',+position.toFixed(2))}>Set end {time(annotation.end||duration)}</button><label><input type="checkbox" checked={loop} disabled={annotation.end<=annotation.start} onChange={e=>setLoop(e.target.checked)}/> Loop</label><button className="text-button" onClick={()=>{update('start',0);update('end',0);setLoop(false)}}>Reset</button></div>
 <details className="source-label" onToggle={e=>setReveal(e.currentTarget.open)} open={reveal}><summary>Reveal dataset performance label</summary><p><span className="pill" style={{color:palette[clip.intended]}}>{clip.intended}</span> Intended acted emotion. No model prediction is being shown.</p></details></article>
 <article className="panel compare"><div className="section-label">03 / COMPARE <span>Same speaker · same text</span></div><select aria-label="Compare another delivery" value={compare} onChange={e=>{compareAudio.current?.pause();setCompare(e.target.value)}}><option value="">Choose another delivery…</option>{peers.map((p,i)=><option key={p.id} value={p.id}>{reveal?p.intended:`Alternative ${i+1}`} · {p.id}</option>)}</select>{comparison&&<><audio ref={compareAudio} key={comparison.url} src={comparison.url} controls onPlay={()=>audio.current?.pause()}/><p>Compare vocal delivery while the transcript stays the same.</p></>}</article>
 <article className="panel context"><div className="section-label">04 / CONTEXT <span>Optional interpretation exercise</span></div><div className="chips">{Object.entries(contexts).map(([k,v])=><button className={context===k?'chosen':''} key={k} onClick={()=>{setContext(k);setStatus('Context changed. Your current rating is an unsaved draft.')}}>{v.label}</button>)}</div>{context==='custom'?<textarea aria-label="Custom context" value={custom} onChange={e=>setCustom(e.target.value)} placeholder="Write a plausible preceding situation…"/>:<p className="scenario">{contextText}</p>}<p className="caution">Added scenarios are authored examples, not original CREMA-D dialogue. Changing context does not change the recording or create a validated experiment.</p></article></section>
 <aside className="annotation panel"><div className="section-label">05 / ANNOTATE</div><h2>What do you hear?</h2><p className="muted">Rate your perception of this expression.</p><label>Perceived emotion<select value={annotation.emotion} onChange={e=>update('emotion',e.target.value)}><option value="">Select an emotion…</option>{emotions.map(e=><option key={e}>{e}</option>)}</select></label><VA/><label>Valence <output>{annotation.valence.toFixed(1)}</output><input type="range" min="-1" max="1" step="0.1" value={annotation.valence} onChange={e=>update('valence',+e.target.value)}/><small>−1 unpleasant → +1 pleasant</small></label><label>Arousal <output>{annotation.arousal.toFixed(1)}</output><input type="range" min="0" max="1" step="0.1" value={annotation.arousal} onChange={e=>update('arousal',+e.target.value)}/><small>0 calm → 1 activated</small></label><label>Confidence <output>{annotation.confidence}/5</output><input type="range" min="1" max="5" value={annotation.confidence} onChange={e=>update('confidence',+e.target.value)}/></label><fieldset><legend>What informed your judgment?</legend>{['Words','Voice / prosody','Context'].map(e=><label className="evidence" key={e}><input type="checkbox" checked={annotation.evidence.includes(e)} onChange={v=>update('evidence',v.target.checked?[...annotation.evidence,e]:annotation.evidence.filter(x=>x!==e))}/>{e}</label>)}</fieldset><label>Listening notes<textarea value={annotation.notes} onChange={e=>update('notes',e.target.value)} placeholder="A pause, a change in pitch, mixed cues…"/></label><button className="primary" disabled={saving||!duration||!!error} onClick={save}>{saving?'Saving…':'Save annotation ↗'}</button><p className="save-status" role="status">{status}</p><p className="caution">VA defaults are starting positions, not model estimates. Saved ratings describe listener judgments.</p></aside></main>}
 <footer><span>Emotion Dynamics Lab / DS7400 · Homework 1</span><span>CREMA-D · ODbL 1.0 / DbCL 1.0 · <a href="https://doi.org/10.1109/TAFFC.2014.2336244" target="_blank" rel="noreferrer">Cao et al., 2014 ↗</a></span></footer></>
}
createRoot(document.getElementById('root')).render(<App/>);
